- 👋 Hi, I’m Apurbo Alfred...
- 👀 I’m interested in python programming language...
- 🏪 I'm Founders and CEO Alfred Ai Corporation...
- 🌱 I’m currently learning ...
- 📫 How to reach me ...

<!---
apurboalfred/apurboalfred is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
